# Generated by Django 4.2.14 on 2024-07-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="default.png", upload_to=""),
        ),
    ]
