# Generated by Django 4.2.14 on 2024-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_post_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
